server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1
  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/mcp-config/mcp-servers-config-1.json
    ollama:
      base-url: http://192.168.31.102:11434
      model: deepseek-r1:7b
      embedding:
        vectorTableName: vector_store
        model: nomic-embed-text
        options:
          num-batch: 768
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-326d5871574a4d68a8d43901758a1a5b
      chat:
        options:
          model: deepseek-chat
      embedding:
        options:
          num-batch: 1536
      embedding-model: text-embedding-ada-002



# Redis
redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
